/**
 * description: 工具类
 * params:
 * author:
 */    

var TimeHandler = {
	formatDateTime : function (datetime) {
		if (datetime == null){
			return "";
		}
		var str = "";
		str += datetime.year + " 年 ";
		str += datetime.monthValue + " 月 ";
		str += datetime.dayOfMonth + " 日 ";
		str += datetime.hour + " 时 ";
		str += datetime.minute + " 分 ";
		str += datetime.second + " 秒 ";
		return str;
	}
};



var SexHandler = {
	formatSex : function (parm) {
		if(parm == '0'){
			return "女";
		}else if (parm == '1'){
			return '男';
		}else {
			return '未知';
		}
	}
};

var StateHandler = {
	formatState : function (parm) {
		if(parm == '1'){
			return "正常";
		}else if (parm == '2'){
			return '已被封禁';
		}else {
			return '未知';
		}
	}
};

function configEmoji() {
	var arr = [{
		"phrase": "[坏笑]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4d/2018new_huaixiao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4d/2018new_huaixiao_org.png",
		"value": "[坏笑]",
		"picid": ""
	}, {
		"phrase": "[笑cry]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4a/2018new_xiaoku_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4a/2018new_xiaoku_thumb.png",
		"value": "[笑cry]",
		"picid": ""
	}, {
		"phrase": "[馋嘴]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fa/2018new_chanzui_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fa/2018new_chanzui_thumb.png",
		"value": "[馋嘴]",
		"picid": ""
	}, {
		"phrase": "[拜拜]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fd/2018new_baibai_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fd/2018new_baibai_thumb.png",
		"value": "[拜拜]",
		"picid": ""
	}, {
		"phrase": "[右哼哼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_youhengheng_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_youhengheng_thumb.png",
		"value": "[右哼哼]",
		"picid": ""
	}, {
		"phrase": "[左哼哼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_zuohengheng_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_zuohengheng_thumb.png",
		"value": "[左哼哼]",
		"picid": ""
	}, {
		"phrase": "[怒骂]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/87/2018new_zhouma_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/87/2018new_zhouma_thumb.png",
		"value": "[怒骂]",
		"picid": ""
	}, {
		"phrase": "[顶]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ae/2018new_ding_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ae/2018new_ding_org.png",
		"value": "[顶]",
		"picid": ""
	}, {
		"phrase": "[微笑]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e3/2018new_weixioa02_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e3/2018new_weixioa02_org.png",
		"value": "[微笑]",
		"picid": ""
	}, {
		"phrase": "[偷笑]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/71/2018new_touxiao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/71/2018new_touxiao_org.png",
		"value": "[偷笑]",
		"picid": ""
	}, {
		"phrase": "[舔屏]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3e/2018new_tianping_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3e/2018new_tianping_thumb.png",
		"value": "[舔屏]",
		"picid": ""
	}, {
		"phrase": "[亲亲]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2c/2018new_qinqin_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2c/2018new_qinqin_thumb.png",
		"value": "[亲亲]",
		"picid": ""
	}, {
		"phrase": "[太开心]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1e/2018new_taikaixin_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1e/2018new_taikaixin_org.png",
		"value": "[太开心]",
		"picid": ""
	}, {
		"phrase": "[挤眼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_jiyan_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_jiyan_org.png",
		"value": "[挤眼]",
		"picid": ""
	}, {
		"phrase": "[衰]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_shuai_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_shuai_thumb.png",
		"value": "[衰]",
		"picid": ""
	}, {
		"phrase": "[感冒]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/40/2018new_kouzhao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/40/2018new_kouzhao_thumb.png",
		"value": "[感冒]",
		"picid": ""
	}, {
		"phrase": "[可怜]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/96/2018new_kelian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/96/2018new_kelian_org.png",
		"value": "[可怜]",
		"picid": ""
	}, {
		"phrase": "[汗]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/28/2018new_han_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/28/2018new_han_org.png",
		"value": "[汗]",
		"picid": ""
	}, {
		"phrase": "[色]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9d/2018new_huaxin_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9d/2018new_huaxin_org.png",
		"value": "[色]",
		"picid": ""
	}, {
		"phrase": "[可爱]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/09/2018new_keai_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/09/2018new_keai_org.png",
		"value": "[可爱]",
		"picid": ""
	}, {
		"phrase": "[钱]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_qian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_qian_thumb.png",
		"value": "[钱]",
		"picid": ""
	}, {
		"phrase": "[思考]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/30/2018new_sikao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/30/2018new_sikao_thumb.png",
		"value": "[思考]",
		"picid": ""
	}, {
		"phrase": "[生病]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3b/2018new_shengbing_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3b/2018new_shengbing_thumb.png",
		"value": "[生病]",
		"picid": ""
	}, {
		"phrase": "[困]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3c/2018new_kun_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3c/2018new_kun_thumb.png",
		"value": "[困]",
		"picid": ""
	}, {
		"phrase": "[互粉]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/86/2018new_hufen02_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/86/2018new_hufen02_org.png",
		"value": "[互粉]",
		"picid": ""
	}, {
		"phrase": "[睡]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e2/2018new_shuijiao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e2/2018new_shuijiao_thumb.png",
		"value": "[睡]",
		"picid": ""
	}, {
		"phrase": "[并不简单]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/aa/2018new_bingbujiandan_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/aa/2018new_bingbujiandan_thumb.png",
		"value": "[并不简单]",
		"picid": ""
	}, {
		"phrase": "[害羞]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_haixiu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_haixiu_org.png",
		"value": "[害羞]",
		"picid": ""
	}, {
		"phrase": "[费解]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2a/2018new_wenhao_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2a/2018new_wenhao_thumb.png",
		"value": "[费解]",
		"picid": ""
	}, {
		"phrase": "[挖鼻]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9a/2018new_wabi_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9a/2018new_wabi_thumb.png",
		"value": "[挖鼻]",
		"picid": ""
	}, {
		"phrase": "[悲伤]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ee/2018new_beishang_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ee/2018new_beishang_org.png",
		"value": "[悲伤]",
		"picid": ""
	}, {
		"phrase": "[打脸]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/cb/2018new_dalian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/cb/2018new_dalian_org.png",
		"value": "[打脸]",
		"picid": ""
	}, {
		"phrase": "[抓狂]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/17/2018new_zhuakuang_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/17/2018new_zhuakuang_org.png",
		"value": "[抓狂]",
		"picid": ""
	}, {
		"phrase": "[哈哈]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8f/2018new_haha_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8f/2018new_haha_thumb.png",
		"value": "[哈哈]",
		"picid": ""
	}, {
		"phrase": "[傻眼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/dd/2018new_shayan_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/dd/2018new_shayan_org.png",
		"value": "[傻眼]",
		"picid": ""
	}, {
		"phrase": "[晕]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/07/2018new_yun_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/07/2018new_yun_thumb.png",
		"value": "[晕]",
		"picid": ""
	}, {
		"phrase": "[鄙视]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/da/2018new_bishi_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/da/2018new_bishi_thumb.png",
		"value": "[鄙视]",
		"picid": ""
	}, {
		"phrase": "[哼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7c/2018new_heng_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7c/2018new_heng_thumb.png",
		"value": "[哼]",
		"picid": ""
	}, {
		"phrase": "[哈欠]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/55/2018new_dahaqian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/55/2018new_dahaqian_org.png",
		"value": "[哈欠]",
		"picid": ""
	}, {
		"phrase": "[泪]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_leimu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_leimu_org.png",
		"value": "[泪]",
		"picid": ""
	}, {
		"phrase": "[怒]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_nu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_nu_thumb.png",
		"value": "[怒]",
		"picid": ""
	}, {
		"phrase": "[闭嘴]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/62/2018new_bizui_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/62/2018new_bizui_org.png",
		"value": "[闭嘴]",
		"picid": ""
	}, {
		"phrase": "[疑问]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b8/2018new_ningwen_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b8/2018new_ningwen_org.png",
		"value": "[疑问]",
		"picid": ""
	}, {
		"phrase": "[白眼]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ef/2018new_landelini_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ef/2018new_landelini_org.png",
		"value": "[白眼]",
		"picid": ""
	}, {
		"phrase": "[吐]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/08/2018new_tu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/08/2018new_tu_thumb.png",
		"value": "[吐]",
		"picid": ""
	}, {
		"phrase": "[黑线]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a3/2018new_heixian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a3/2018new_heixian_thumb.png",
		"value": "[黑线]",
		"picid": ""
	}, {
		"phrase": "[委屈]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a5/2018new_weiqu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a5/2018new_weiqu_thumb.png",
		"value": "[委屈]",
		"picid": ""
	}, {
		"phrase": "[笑而不语]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2d/2018new_xiaoerbuyu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2d/2018new_xiaoerbuyu_org.png",
		"value": "[笑而不语]",
		"picid": ""
	}, {
		"phrase": "[阴险]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9e/2018new_yinxian_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9e/2018new_yinxian_org.png",
		"value": "[阴险]",
		"picid": ""
	}, {
		"phrase": "[嘘]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b0/2018new_xu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b0/2018new_xu_org.png",
		"value": "[嘘]",
		"picid": ""
	}, {
		"phrase": "[嘻嘻]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/33/2018new_xixi_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/33/2018new_xixi_thumb.png",
		"value": "[嘻嘻]",
		"picid": ""
	}, {
		"phrase": "[爱你]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_aini_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_aini_org.png",
		"value": "[爱你]",
		"picid": ""
	}, {
		"phrase": "[吃惊]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/49/2018new_chijing_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/49/2018new_chijing_org.png",
		"value": "[吃惊]",
		"picid": ""
	}, {
		"phrase": "[污]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/10/2018new_wu_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/10/2018new_wu_thumb.png",
		"value": "[污]",
		"picid": ""
	}, {
		"phrase": "[鼓掌]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_guzhang_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_guzhang_thumb.png",
		"value": "[鼓掌]",
		"picid": ""
	}, {
		"phrase": "[憧憬]",
		"type": "face",
		"url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c9/2018new_chongjing_org.png",
		"hot": false,
		"common": true,
		"category": "",
		src: "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c9/2018new_chongjing_org.png",
		"value": "[憧憬]",
		"picid": ""
	}];
	return arr;
}